APP_CONFIG_FILE = 'Конфигуратор приложения.xlsx'
APP_CONFIG_MAIN_SETTINGS_SHEET = 'Настройки приложения'
APP_CONFIG_URLS_TO_PROTOCOLS_SHEET = 'Ссылки на протоколы'

RANK_CONFIG_FILE = 'Конфигуратор формулы ранга.xlsx'
RANK_CONFIG_MAIN_SETTINGS_SHEET = 'Общие настройки'
RANK_CONFIG_RACE_TYPE_SHEET = 'Коэффициент вида старта'
RANK_CONFIG_RACE_LEVEL_SHEET = 'Коэффициент уровня старта'
RANK_CONFIG_GROUP_RANK_SHEET = 'Ранг группы'
RANK_CONFIG_PENALTY_LACK_RACES_SHEET = 'Штраф за отсутствие старта'
RANK_CONFIG_PENALTY_NOT_STARTED_SHEET = 'Штраф за не стартовал'
RANK_CONFIG_PENALTY_LEFT_RACE_SHEET = 'Штраф за снят'
